services:
  - type: web
    name: unlimited-storage
    env: node
    plan: free
    buildCommand: npm install && cd client && npm install && npm run build
    startCommand: node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
